version: '3.9'

services:
  heuristics_based_detection_service:
    image: 064427434392.dkr.ecr.us-east-1.amazonaws.com/heuristics_based_detection_service:latest
    container_name: heuristics_based_detection_service
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '${DEV_SYSTEM_PATH_TO_MODEL}:/app/model/lgb.model'
    environment:
      - ENVIRONMENT=DEVELOPMENT
    env_file:
      - .env
      - src_env/dev/.env
    ports:
      - '${DEV_SYSTEM_APP_PORT}:${DEV_APP_PORT}/tcp'
    expose:
      - '${DEV_APP_PORT}/tcp'
    command: gunicorn main:app --worker-tmp-dir /dev/shm -b ${DEV_APP_HOST}:${DEV_APP_PORT} -w ${DEV_APP_WORKERS} -t ${DEV_APP_TIMEOUT} --graceful-timeout $DEV_APP_GRACEFUL_TIMEOUT -k uvicorn.workers.UvicornWorker
